[package]
name = "lambda_auto_likes"
version = "0.1.0"
authors = ["snicmakino <mkn.fj.cd@gmail.com>"]

[dependencies]
twitter-api = "*"
error-chain = "0.10"
oauth-client = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
