[package]
name = "lambda_auto_likes"
version = "0.1.0"
authors = ["snicmakino <mkn.fj.cd@gmail.com>"]

[dependencies]
rust-apex = "0.3"
serde_json = "1"
failure = "0.1"
egg-mode = "0.12.0"
chrono = "0.4.0"
tokio-core = "0.1.6"
futures = "0.1.14"
